name: CI Build on development branch 

on:
    push:
        branches:
            - development

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            CONNECTIONSTRINGS__DefaultConnection: ${{ vars.DB_CONNECTION }} 

        steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-dotnet@v4
           with:
            dotnet-version: 8.x
         - run: dotnet build
         - run: dotnet test
         - name: Check connection string variable
           run: 'echo "Connection string is: $CONNECTIONSTRINGS__DefaultConnection"'
        
